### ISSUE TITLE
make conto 4.7 install possible

### ISSUE THREAD

**Issue by Misco** [heimrichhannot/contao-google-maps-bundle#2]
at the moment all your bundles are not working for 4.7 because they ty to use old symfony. Would be glad if i can test your bundles in contao 4.7

**Comment by Defcon0** [comment]
Hello @Misco,

we'll port our modules after the release of the next LTS version (4.9).

**Comment by fritzmg** [comment]
What do you mean by "port"? You already allow Contao >=4.4,<5 in your composer.json, but your requirement to the symfony/framework-bundle is unnecessarily restricting - unless you rely on functionality, that is not available in Version 4.x of symfony/framework-bundle.

**Comment by Defcon0** [comment]
We‘ll restrict our modules to 4.4 ... 4.9 when we make it compatible for 4.9. We should’ve done that for v4.4 already. It was a mistake.
