### ISSUE TITLE
Polygone

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-google-maps-bundle#21]
Hi, wollte nur fragen, ob in nächster Zeit die Umsetzung der Darstellung von Polygonen geplant ist? Ich hätte einen Kunden, der dies gerne nutzen würde. Falls ich mit einem monetären Beitrag helfen kann, gebt mir gerne Bescheid.

**Comment by koertho** [comment]
Hi, sorry das es hier keine Antwort gab. Geplant ist es nicht, wir machen neue Features immer Projekt-Bezogen. Ein PR ist aber immer willkommen :)
Ein monitärer Beitrag hilft leider nicht, wenn es das Zeit-Budget das eigentliche Problem ist, aber danke dir :)

**Comment by operatorone** [comment]
Moin, lieben Dank für deine Rückmeldung. Für einen PR reicht leider mein Knowledge nicht für die Umsetzung aus, mal sehen, ob ich hier eine Möglichkeit bzw. jemanden finde, der das umsetzen könnte.

**Comment by koertho** [comment]
Wir arbeiten gerade einen neuen Kollegen ein, vielleicht schafft er es, es sich mal anzuschauen, kann aber nichts versprechen.
