### ISSUE TITLE
4.13.4 - Installation fehlerhaft

### ISSUE THREAD

**Issue by sproellwp** [heimrichhannot/contao-google-maps-bundle#22]
Unter 4.13.4 bleibt die Installation bei der Aktualisierung der DB hängen (siehe Screenshot).
![Bildschirmfoto 2022-06-03 um 11 58 06](https://user-images.githubusercontent.com/56022864/171833208-8db7fcf4-b186-47bd-b48f-c319bff3939f.png)

**Comment by koertho** [comment]
Hier das Issue dazu: https://github.com/contao/contao/issues/4943

**Comment by koertho** [comment]
Behoben in 2.8.2. Danke für's melden!
