### ISSUE TITLE
Google Map doesn't load / New maintained google-map packages

### ISSUE THREAD

**Issue by bresam** [heimrichhannot/contao-google-maps-bundle#4]
Hi, i could see on your website that your google map isn't working.
Take a look at [ivory/google-map](https://packagist.org/packages/ivory/google-map) and [ivory/google-map-bundle](https://packagist.org/packages/ivory/google-map-bundle)

I've fixed the issues and will maintain both of them.

**Comment by Defcon0** [comment]
Hello,

great news. Did you contact the owners of the original repos to take them over?

Bye Defcon0

**Comment by bresam** [comment]
Hi @Defcon0 Yes i did contact him several times over the last 4 weeks.
Others also tried but he never responded.
So i decided to publish it on my own.

**Comment by Defcon0** [comment]
May I ask how did you find us and this bundle?

**Comment by bresam** [comment]
Sure :-)
I've checked the network tree of google-map package and contacted the repo owners which had commits within the last year.
In your case I even looked at your website to see if you use the google-map package for the company website.

**Comment by fenepedia** [comment]
Hey, I use your extension for contao 4.9. The Maps don't load any more. Can you require the working repositorys from @bresam ?

**Comment by fenepedia** [comment]
Can you give me information when you can fix this?

**Comment by fritzmg** [comment]
@bresam unfortunately `ivory/google-map ` and `ivory/google-map-bundle` are not compatible with Symfony 4 yet, so it's not really usable for higher Contao versions (for this extension).

**Comment by bresam** [comment]
@fritzmg i'm aware of that, the roadmap is to support symfony 4 and 5 within next 6 weeks (fully upgraded and unit-tested). if your issue just depends on composer requirement versions i can publish an early 4.0.0 version with these changes. Would that help you?

**Comment by bresam** [comment]
You are using  anisimov/google-map-bundle right now, i could add the same changes he did and publish that today.

**Comment by fritzmg** [comment]
Both of that would probably help to get this along, yes :)

**Comment by fenepedia** [comment]
@bresam This would be great!

**Comment by Defcon0** [comment]
@koertho Will take care of the switch of the bundles when a new tagged version is available. We try our best to do that as soon as possible. Of course, we have lots of other time constraints, as well.

**Comment by bresam** [comment]
@koertho dependencies have been updated. I think it should work fine. If you ran into any issues just contact me.

**Comment by koertho** [comment]
I just release 2.0.0-beta3 which is now based on the library and bundle from @bresam and has undergone some code enhancements and upgrades with a few breaking changes, so it will be a new major version. Please check the changelog and the upgrade notices for more information. There are still some things I want to improve, but for now you could test it if everything works as expected. I also not tested it with contao 4.4, but I tried to keep it compatible.

**Comment by fenepedia** [comment]
Thx. Map works again
