### ISSUE TITLE
Google Map Karte wird nicht angezeigt

### ISSUE THREAD

**Issue by tedigital** [heimrichhannot/contao-google-maps-bundle#5]
Hallo,

ich habe die Erweiterung heimrichhannot/contao-google-maps-bundle in der Version 1.4.1 unter Contao 4.4 installiert und konfiguriert. Auf der Webseite wird die Karte nicht ausgegeben egal ob das Bundle als Modul oder Inhaltselement eingebunden wird. Der HTML-Code ist in der Webseite vorhanden, lediglich die Überschrift wird auf der Seite sichtbar dargestellt. Daraufhin hatte ich versucht eine der Beta-Versionen zu installieren, aber jedes mal wird wird die Installation mit nachfolgender Fehlermeldung abgebrochen.
Woran liegt es, dass die Karte nicht angezeigt wird und wie kann ich dies beheben?
Außerdem, wieso bricht jedes mal die Installation der Beta-Version ab?
Danke!

Gruß
Thomas

$ /usr/bin/php7.2 -q -d allow_url_fopen=1 -d memory_limit=2048M -d suhosin.executor.include.whitelist="phar://,http://,https://" /is/htdocs/wp1163178_BIQN3TMV92/www.musikverein-hirschzell.de/contaosub/web/contao-manager.phar.php composer require heimrichhannot/contao-google-maps-bundle=^2.0@beta --no-suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Using config.component-dir has been deprecated. Please use extra.contao-component-dir instead.
/is/htdocs/wp1163178_BIQN3TMV92/www.musikverein-hirschzell.de/contaosub/composer.json has been updated

# Process terminated with exit code 0
# Result: OK

> Resolving dependencies using Composer Cloud v2.4.3

[7.0MiB/0.24s] Loading composer repositories with package information
[7.4MiB/0.30s] Updating dependencies
[3252.4MiB/59.14s] Your requirements could not be resolved to an installable set of packages.
[3252.4MiB/59.15s] 
  Problem 1
    - Conclusion: don't install contao/core-bundle 4.10.0
    - Conclusion: don't install contao/newsletter-bundle 4.4.49
    - Conclusion: don't install heimrichhannot/contao-google-maps-bundle 2.0.0-beta7
    - Conclusion: don't install heimrichhannot/contao-google-maps-bundle 2.0.0-beta6
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta2 requires contao/core-bundle ^4.9 -> satisfiable by contao/core-bundle[4.10.0, 4.9.0, 4.9.1, 4.9.2, 4.9.3, 4.9.4, 4.9.5].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta1 requires contao/core-bundle ^4.9 -> satisfiable by contao/core-bundle[4.10.0, 4.9.0, 4.9.1, 4.9.2, 4.9.3, 4.9.4, 4.9.5].
    - Can only install one of: contao/core-bundle[4.9.0, 4.4.49].
    - Can only install one of: contao/core-bundle[4.9.1, 4.4.49].
    - Can only install one of: contao/core-bundle[4.9.2, 4.4.49].
    - Can only install one of: contao/core-bundle[4.9.3, 4.4.49].
    - Can only install one of: contao/core-bundle[4.9.4, 4.4.49].
    - Can only install one of: contao/core-bundle[4.9.5, 4.4.49].
    - contao/newsletter-bundle 4.4.49 requires contao/core-bundle 4.4.49 -> satisfiable by contao/core-bundle[4.4.49].
    - Conclusion: don't install contao/core-bundle 4.4.49
    - Conclusion: don't install twig/twig v1.42.5|install heimrichhannot/contao-google-maps-bundle 2.0.0-beta1|install heimrichhannot/contao-google-maps-bundle 2.0.0-beta2
    - Conclusion: don't install twig/twig v1.43.0|install heimrichhannot/contao-google-maps-bundle 2.0.0-beta1|install heimrichhannot/contao-google-maps-bundle 2.0.0-beta2
    - Conclusion: don't install twig/twig v1.43.1|install heimrichhannot/contao-google-maps-bundle 2.0.0-beta1|install heimrichhannot/contao-google-maps-bundle 2.0.0-beta2
    - Conclusion: don't install twig/twig v1.42.4
    - Conclusion: don't install heimrichhannot/contao-google-maps-bundle 2.0.0-beta5
    - Conclusion: don't install twig/twig v1.42.3
    - Installation request for kriswallsmith/assetic (locked at v1.4.0) -> satisfiable by kriswallsmith/assetic[v1.4.0].
    - Installation request for symfony/mime (locked at v5.0.8) -> satisfiable by symfony/mime[v5.0.8].
    - Installation request for contao/newsletter-bundle (locked at 4.4.49, required as ^4.4) -> satisfiable by contao/newsletter-bundle[4.4.49].
    - Conclusion: don't install heimrichhannot/contao-google-maps-bundle 2.0.0-beta4
    - contao/core-bundle 4.4.49 requires twig/twig ^1.26 -> satisfiable by twig/twig[v1.43.1, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.33.1, v1.33.2, v1.34.0, v1.34.1, v1.34.2, v1.34.3, v1.34.4, v1.35.0, v1.35.1, v1.35.2, v1.35.3, v1.35.4, v1.36.0, v1.37.0, v1.37.1, v1.38.0, v1.38.1, v1.38.2, v1.38.3, v1.38.4, v1.39.0, v1.39.1, v1.40.0, v1.40.1, v1.41.0, v1.42.0, v1.42.1, v1.42.2, v1.42.3, v1.42.4, v1.42.5, v1.43.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.26.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.26.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.27.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.28.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.28.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.28.2].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.29.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.30.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.31.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.32.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.33.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.33.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.33.2].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.34.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.34.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.34.2].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.34.3].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.34.4].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.35.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.35.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.35.2].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.35.3].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.35.4].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.36.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.37.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.37.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.38.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.38.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.38.2].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.38.3].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.38.4].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.39.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.39.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.40.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.40.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.41.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.42.0].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.42.1].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.42.2].
    - heimrichhannot/contao-google-maps-bundle 2.0.0-beta3 conflicts with twig/twig[v1.43.1].
    - Installation request for heimrichhannot/contao-google-maps-bundle ^2.0@beta -> satisfiable by heimrichhannot/contao-google-maps-bundle[2.0.0-beta1, 2.0.0-beta2, 2.0.0-beta3, 2.0.0-beta4, 2.0.0-beta5, 2.0.0-beta6, 2.0.0-beta7].

[3252.5MiB/59.15s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[535.5MiB/61.60s] Memory usage: 535.5MB (peak: 3256.83MB), time: 61.61s.
[535.5MiB/61.61s] Finished Composer Cloud resolving.

# Cloud Job ID Fg3sGLl1mlOGLJqLxegKBx2ZVBNIMJsbj0To4o3Gsgo4ZK8XrXThU8aTz0bWQKUnjjrmJQLDtNExll514EmFROoJ4Jyxih0lskhTS2B failed

---

**Comment by Defcon0** [comment]
Kannst du bite die letzte Beta versuchen, zu installieren? @fritzmg hat einen fehlerhaften Conflict behoben und wir haben es gemerget.

Bzgl. dem Problem, dass keine Map ausgegeben wird: wird ein Canvas ausgegeben? kannst du einen Screenshot posten, wo man sich den Code anschauen kann, der erzeugt wird? Oder gibt es einen Link?

**Comment by tedigital** [comment]
Danke für die Rückmeldung, hat leider nicht geklappt. Den Fehlerbericht habe ich am Ende des Posts beigefügt.

Zunächst aber der Link zu der betreffenden Webseite: [http://sub.musikverein-hirschzell.de/kontakt.html](url)


Gruß
Thomas


Fehlerbericht:
`$ /usr/bin/php7.2 -q -d allow_url_fopen=1 -d memory_limit=2048M -d suhosin.executor.include.whitelist="phar://,http://,https://" /is/htdocs/wp1163178_BIQN3TMV92/www.musikverein-hirschzell.de/contaosub/web/contao-manager.phar.php composer require heimrichhannot/contao-google-maps-bundle=^2.0@beta --no-suggest --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Using config.component-dir has been deprecated. Please use extra.contao-component-dir instead.
/is/htdocs/wp1163178_BIQN3TMV92/www.musikverein-hirschzell.de/contaosub/composer.json has been updated

# Process terminated with exit code 0
# Result: OK


> Resolving dependencies using Composer Cloud v2.4.3

# Job ID 5TscHgPLowtl1jyIRWcelcaZZNXMHLgMAMRAOkuERn73OoMGBnZ5IZQz0LBA7RyV6f5HMYi1TBV7egeyCNXCJAWyHYLnRRJUL886VDMo8M93hf completed in 81 seconds
# Memory usage: 539.52MB (peak: 3301.48MB), time: 79.8s.

$ /usr/bin/php7.2 -q -d allow_url_fopen=1 -d memory_limit=2048M -d suhosin.executor.include.whitelist="phar://,http://,https://" /is/htdocs/wp1163178_BIQN3TMV92/www.musikverein-hirschzell.de/contaosub/web/contao-manager.phar.php composer install --prefer-dist --no-dev --no-progress --no-suggest --no-ansi --no-interaction --optimize-autoloader

Using config.component-dir has been deprecated. Please use extra.contao-component-dir instead.
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
Compiling component files
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class

In DefinitionErrorExceptionPass.php line 37:
                                                                               
  Cannot autowire service "HeimrichHannot\GoogleMapsBundle\Manager\MapManager  
  ": argument "$eventDispatcher" of method "__construct()" has type "Symfony\  
  Contracts\EventDispatcher\EventDispatcherInterface" but this class was not   
  found.                                                                       
                                                                               

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 4 updates, 0 removals
  - Updating symfony/symfony (v3.4.43 => v3.4.44): As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
Loading from cache
  - Updating symfony/http-client (v5.1.3 => v5.1.4): Loading from cache
  - Updating heimrichhannot/contao-utils-bundle (2.177.3 => 2.177.6): Loading from cache
  - Updating heimrichhannot/contao-google-maps-bundle (1.4.1 => 2.0.0-beta8): Loading from cache
Package crossjoin/browscap is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Deprecation Notice: Class LionelM\NewsletterExportBundle\NewsletterExport located in ./vendor/lionel/newsletter-export/src/Resources/contao/classes/NewsletterExport.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///is/htdocs/wp1163178_BIQN3TMV92/www.musikverein-hirschzell.de/contaosub/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Autoload/ClassMapGenerator.php:201
> ComponentInstaller\Installer::postAutoloadDump
23 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

In ScriptHandler.php line 113:
                                                                               
  An error occurred while executing the "contao:install-web-dir" command:      
  In DefinitionErrorExceptionPass.php line 37:                                 
                                                                               
                                                                               
    Cannot autowire service "HeimrichHannot\GoogleMapsBundle\Manager\MapManag  
  er                                                                           
    ": argument "$eventDispatcher" of method "__construct()" has type "Symfon  
  y\                                                                           
    Contracts\EventDispatcher\EventDispatcherInterface" but this class was no  
  t                                                                            
    found.                                                                     
                                                                               

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>...]


# Process terminated with exit code 1
# Result: General error


---

### Der Hintergrundprozess wurde unerwartet beendet ###`

**Comment by Defcon0** [comment]
Ich habe soeben den Fehler im 2.0er-Bundle behoben. Bitte teste mal die Version 2.0.0-beta9. Ich habe es in einem frischen 4.4er-Projekt getestet. Dort funktioniert alles.

**Comment by tedigital** [comment]
Also, die Installation von der Version 2.0.0-beta9 hat jetzt geklappt.
Aber die Google Maps Karte wird dennoch nicht ausgegeben, außer der Überschrift.
Link zur Webseite: [http://sub.musikverein-hirschzell.de/kontakt.html](url)

Danke!

Gruß
Thomas

**Comment by Defcon0** [comment]
Doch, es geht bereits. Aber es kann sein, dass du beim Seitenverhältnis nichts angegeben hast :-) Gib dort bitte mal bspw. 16:9 ein. Wenn ich auf dem map_canvas die CSS-Werte:

```
    width: 100px;
    height: 100px;
```

Ich glaube, wir setzen die Default-Werte beim Seitenverhältnis dann mal auf 16:9, damit man darüber nicht stolpert ;-)

setze, wird die Map korrekt angezeigt. Allerdings musst du am API-Key, wie in der Konsole steht, eine Zahlungsmethode hinterlegen, damit es geht. Das ist eine Änderung von Google von vor ca. 1 Jahr.

**Comment by tedigital** [comment]
Es hat alles soweit geklappt, nur die Zahlungsmethode habe ich noch nicht eingerichtet. Besten Dank für die Unterstützung.
Jetzt habe ich vermutlich noch ein kleines Problem, weil ich das Google Map Modul als Inserttag einbinden möchte aufgrund meines Designs. Nach langen Recherchen ohne Erfolg ist mir nur diese Methode eingefallen. `{{insert_module::710}}` Dieses Inserttag wird in den HTML-Code eingebunden. Nur habe ich jetzt das gleiche Problem wieder wie zuvor, dass nur die Überschrift auf der Webseite angezeigt wird. Ich habe in den Einstellungen keine Veränderung vorgenommen unter Größenmodus. Hier ist nach wie vor ein Seitenverhältnis von 16:9 eingetragen. An was könnte dies liegen und gibt es dafür eine Lösung?
Danke!

Gruß
Thomas

**Comment by Defcon0** [comment]
Hi Thomas,

ich denke, wir haben den Fehler gefunden. Die Reihenfolge der Callbacks führte bei der Einbindung per Insert-Tag zu Problemen.

Mit der aktuellen Version sollte es passen (2.0.0-beta10).

Danke fürs Testen!

**Comment by tedigital** [comment]
Danke für die schnelle Hilfe, werde es gleich mal ausprobieren.
In der Zwischenzeit ist mir noch was aufgefallen und weiß nicht wie ich das lösen kann. 
Wenn man in die Karte eine Infoblase einfügt dann wird die im Kartenausschnitt auf der Webseite nicht mittig dargestellt, sondern immer in einem Abstand von 10 Pixel zu den Buttons auf der rechten Seite. Aktiviert man das Vollbild, so ist die Infoblase mittig zentriert. Gibt es hierfür eine Einstellung die ich vornehmen kann?
Danke!

Gruß
Thomas

**Comment by Defcon0** [comment]
Naja, das ist dann schon relativ weit in deinem eigenen Code drin, da kann ich dir leider nix zu sagen, sorry ;-)
