### ISSUE TITLE
Add better error handling, if API code is missing

### ISSUE THREAD

**Issue by rabauss** [heimrichhannot/contao-google-maps-bundle#8]
Currently you won't get a nice error message in the front end, if you missed adding an API key!
You only get a type warning because `$apiKey` is `null` here:
https://github.com/heimrichhannot/contao-google-maps-bundle/blob/fa64af7239c188887f9edacf142bf818618c7051/src/Manager/OverlayManager.php#L72

**Comment by Defcon0** [comment]
Fixed in latest beta. Thanks for reporting ;-)
