### ISSUE TITLE
Styles werden nicht angenommen.

### ISSUE THREAD

**Issue by Webstylerin** [heimrichhannot/contao-google-maps-bundle#9]
Hallo,

ich möchte der Google Map ein paar neue Farben geben. Dazu gibt es ja in der Kartenkonfiguration ein eigenes Feld.

Den JSON-Code habe ich von https://mapstyle.withgoogle.com/ genommen, das Feld meckert auch nicht über Fehler, aber es ändert sich im Frontend nichts an der Karte.

Muss ich den Code noch bearbeiten? Fehlt noch eine Einstellung?

Ein Ausschnitt des Codes:
![Bildschirmfoto 2021-09-04 um 19 14 19](https://user-images.githubusercontent.com/3033160/132102992-fcfc400a-b15c-4d51-a23e-44bf85fc380e.png)

VG
Nicole

**Comment by Webstylerin** [comment]
Ich habe heute noch mal versucht die Styles hinzubekommen. Der Rest läuft ja super.

Es scheint egal zu sein, was ich da rein schreibe, das Ergebnis im HTML-Code der Webseite ist immer "styles": null,.

Ausschnitt:
`"mapTypeId":google.maps.MapTypeId.ROADMAP,"styles":null,"disableDoubleClickZoom":!1,`

Es wäre wichtig für mich zu wissen, ob ich die Styles falsch eingebe, das Feld komplett falsch verstanden habe oder es ein Fehler in der Erweiterung ist.

LG
Nicole

**Comment by rabauss** [comment]
Also die `styles` werden aktuell kodiert gespeichert, aber leider nicht dekodiert!
Ich habe einen möglichen Fix als PR #11 vorbereitet.

Ich konnte es nur mit meinen Styles testen, die ich mal bei dlh im Einsatz hatte. Es wäre hilfreich, wenn die Styles von @Webstylerin hier nicht nur als Screenshot verfügbar wären ;-)

**Comment by Webstylerin** [comment]
> Ich konnte es nur mit meinen Styles testen, die ich mal bei dlh im Einsatz hatte. Es wäre hilfreich, wenn die Styles von @Webstylerin hier nicht nur als Screenshot verfügbar wären ;-)

Klar, hier sind sie. :)
[styles.txt](https://github.com/heimrichhannot/contao-google-maps-bundle/files/7148530/styles.txt)

Vielen Dank @rabauss.

**Comment by rabauss** [comment]
I guess it's working with the given styles and my fix ;-)

![image](https://user-images.githubusercontent.com/14016098/132966131-7b14d6d3-a9cf-473e-8ed7-f648a6ab7d31.png)

**Comment by Webstylerin** [comment]
Seht gut aus! Wie/wann komme ich an den Fix ran? :)

**Comment by Defcon0** [comment]
Keine Sorge, wir schauen uns das noch diese Woche an ;-) Danke für eure Mitarbeit!

**Comment by Webstylerin** [comment]
Perfekt! Vielen Dank fürs Nachsehen und den kommenden Fix.
